
--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, 
SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender
ORDER BY gender ASC



-- Q2. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
item_purchased,
CAST(ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2)AS DECIMAL(10,2)) AS [Average Product Rating]
FROM customer
GROUP BY item_purchased
ORDER BY [Average Product Rating] DESC



--Q3. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
shipping_type,
CAST(ROUND(AVG(CAST(purchase_amount AS DECIMAL(12,2))), 2)AS DECIMAL(12,2)) AS Avg_Purchase_Amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type



--Q4. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
subscription_status,
COUNT(customer_id) AS total_customers,
CAST(ROUND(AVG(CAST(purchase_amount AS DECIMAL(10,2))), 2) AS DECIMAL(10,2)) AS avg_spend,
ROUND(SUM(CAST(purchase_amount AS DECIMAL(10,2))), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC



--Q5. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
item_purchased,
CAST(ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)AS DECIMAL(6,2)) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC



--Q6. Segment customers into New, Returning, and Loyal based on their total 
--    number of previous purchases, and show the count of each segment.  
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

SELECT customer_segment,count(*) AS number_of_customers
FROM customer_type 
GROUP BY customer_segment




--Q7. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3




--Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status




--Q9. What is the revenue contribution of each age group? 
SELECT 
age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC






